### PR TITLE
Update mopidy

### PR DESCRIPTION
**Pull request by martiert**
These patches updates mopidy to v2.0.0, which uses gstreamer 1 instead of 0.10

### CODE REVIEW

**Comment by mrueg** [comment]
Thanks, will merge in later.

**Comment by mrueg** [comment]
Having a closer look at it. Why did you remove the slot and gstreamer dependencies? Keep in mind It requires >=gstreamer-1.2.3:1 now.

**Comment by martiert** [comment]
The versioning on gst and slots should at least be added back, however with [http,mp3] use flags on gst-plugins-meta it will pull inn what is needed.

If you want to I can put back the explicit gst-plugins, not sure what the need for both gst-plugins-good and gst-plugins-meta is though.

Also, the gst-plugins-bad is not necessary, as mopidy does not have a dependency on it.

**Comment by mrueg** [comment]
Do you want me to fix it and close this PR or do you wanna rebase your PR?

**Comment by martiert** [comment]
I'll fix it and rebase my PR

**Comment by martiert** [comment]
Added version constraints on gst-python and gst-plugins-meta, as well as chose the correct slot

**Comment by mrueg** [comment]
Thanks! Applied as 1225bfcdfc93fbc6ae47c02f315ee9d5a9c012b7 and 48f9843a176e98be8f7ffd4687053a7848f71d91

**Pull request closed without merging**
